name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_FIELD_08082A103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: '/dist'
          output_location: ''
          skip_app_build: true